---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.crd.liuqhahah.com
  resources:
  - snapshotschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.crd.liuqhahah.com
  resources:
  - snapshotschedules/finalizers
  verbs:
  - update
- apiGroups:
  - batch.crd.liuqhahah.com
  resources:
  - snapshotschedules/status
  verbs:
  - get
  - patch
  - update
